---
- name: Installing boto in Controller Machine
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: Installing pip
      easy_install:
        name: pip
        state: latest

    - name: Installing Boto
      pip:
        name: boto
