---


- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: gather facts about "{{SERVER}}" AMIs
      ec2_ami_facts:
        region: "{{ REGION }}"
        filters:
          "tag-value": "{{ SERVER }}" 
      register: ami_facts

    - debug:
        var: ami_facts

    - name: gather facts about Security Group
      ec2_group_info:
        region: "{{ REGION }}"
        filters:
          "tag-value": "{{ ENVIRONMENT }}" 
          "tag-value": "{{ REGION }}" 
          "tag-value": "{{ SERVER }}"
      register: sg_facts

    - debug: 
        var: sg_facts
    
    - name: gather facts about subnet
      ec2_vpc_subnet_facts:
        region: "{{ REGION }}"
        filters:
          "tag-value": "{{ PURPOSE }}"

    - debug:
        var: subnet_facts

















    
