---


- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: gather facts about "{{SERVER}}" AMIs
      ec2_ami_facts:
        region: "{{ REGION }}"
        filters:
          "tag-value": "{{ SERVER }}" 
      register: ami_facts

    - debug:
        var: ami_facts

    - name: gather facts about Security Group
      ec2_group_facts:
        region: "{{ REGION }}"
        filters:
          "tag-value": 
           with_items:
             - " {{ ENVIRONMENT }}" 
             - " {{ REGION }}" 
             - " {{ SERVER }}"
      register: sg_facts

    - debug: 
        var: sg_facts

    
