---


- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: gather facts about "{{SERVER}}" AMIs
      ec2_ami_facts:
        region: "{{ REGION }}"
        filters:
          "tag-value": "{{ SERVER }}" 
      register: ami_facts

    - debug:
        var: ami_facts

    - name: gather facts about Security Group
      ec2_group_info:
        region: "{{ REGION }}"
        filters:
          "tag-value": "{{ ENVIRONMENT }}" 
          "tag-value": "{{ REGION }}" 
          "tag-value": "{{ SERVER }}"
      register: sg_facts

    - debug: 
        var: sg_facts
    
    - name: gather facts about subnet
      ec2_vpc_subnet_facts:
        region: "{{ REGION }}"
        filters:
          "tag-value": "{{ PURPOSE }}"
      register: subnet_facts
    - debug:
        var: subnet_facts
    - name: Create "{{ SERVER}}" Instance
      ec2:
        key_name: mac
        instance_type: t2.micro
        image_id: "{{ ami_facts_image_id }}"
        wait: yes
        group_id: "{{ sg_facts.group_id }}"
        count: 1
        vpc_subnet_id: "{{ subnet_facts.subnet_id }}"
        assign_public_ip: yes















    
