---


- name: Creating Launch_Config
  hosts: localhost
  become: true
  gather_facts: False
  tasks:
    - name: gather facts about "{{SERVER}}" AMIs
      ec2_ami_facts:
        filters:
          "tag_value": "{{ SERVER }}" 
      register: ami_facts

    - debug:
        var: ami_facts

    - name: gather facts about Security Group
      ec2_group_facts:
       filters:
         "tag_value": "{{ ENVIRONMENT }} | {{ REGION }} | {{ SERVER }}"
      register: sg_facts

    - debug: 
        var: sg_facts

    
