---


- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: gather facts about "{{SERVER}}" AMIs
      ec2_ami_facts:
        region: "{{ REGION }}"
        filters:
          "tag-value": "{{ SERVER }}" 
      register: ami_facts

    - debug:
        var: ami_facts
    
 #   - name: Set Service AMI Builder Image for "{{ SERVICE }}"
 #     set_fact:
 #       IMAGE_ID: "{{ ami_facts.image_id }}"
    
    - name: gather facts about Security Group
      ec2_group_info:
        region: "{{ REGION }}"
        filters:
          "tag-value": "{{ ENVIRONMENT }}" 
          "tag-value": "{{ REGION }}" 
          "tag-value": "{{ SERVER }}"
      register: sg_facts

    - debug: 
        var: sg_facts
    
    - name: gather facts about subnet
      ec2_vpc_subnet_facts:
        region: "{{ REGION }}"
        filters:
          "tag-value": "{{ PURPOSE }}"
      register: subnet_facts
    - debug:
        var: subnet_facts
    - name: Create "{{ SERVER}}" Instance
      ec2:
        key_name: Mac
        instance_type: t2.micro
        image: "{{ ami_facts.results.0.ami_id }}" #ami-00cb043dfe625c3f3
        wait: yes
        group: "{{ sg_facts.results.0.group_id }}"
        count: 1
        vpc_saubnet_id: "{{ subnet_facts.results.0.subnet_id }}"
        assign_public_ip: yes















    
